### PR TITLE
Add Support goldsrc .MAP format

### PR DESCRIPTION
**Pull request by G2Pavon**
Basic implementation to export to valve 220 .MAP format the standard goldsrc format used in Valve Hammer Editor 3.5/3.4, JACK and TrenchBroom.

### CODE REVIEW

**Comment by lewa-j** [comment]
Maybe should make it optional. Selecting one or another

**Comment by G2Pavon** [comment]
tell me what you think. obj and map are now optional, also added -novmf. I also added console messages.

```./osm2vmf```
image

```./osm2vmf asd```
image

```./osm2vmf ny_manhattan1.osm -novmf```
image

**Comment by G2Pavon** [comment]
I added a small fix. Now -novmf validation is outside of the args iteration check. 

Before: when you pass -novmf as the first optional arg (like `-novmf -obj` instead of `-obj -novmf`  ) it returns the message '-novmf arg is only valid if -obj or -map is specified.'

Now: optional arguments can be passed in any order.

**Comment by lewa-j** [comment]
Perfect! Thanks

**Pull request merged**
